### ISSUE TITLE
Machine Learning notebook looks like it is corrupt

### ISSUE THREAD

**Issue by jonathanmorgan** [CSSIP-AIR/Big-Data-Workbooks#9]
Hello,

When you try to open the Machine Learning notebook in github, you get an error (https://github.com/CSSIP-AIR/Big-Data-Workbooks/blob/master/07.%20Machine%20Learning/Machine%20Learning.ipynb).

When I download it to my computer (a mac), I get that it is not a JSON file, and there is a "\U" at the beginning of the string...

Not sure what is going on, but something in the updates since the class looks like it caused a problem.

Thanks,

Jon

**Comment by ahmademad** [comment]
There was a malformed json. It is now fixed
